### ISSUE TITLE
Ability to customize links

### ISSUE THREAD

**Issue by obadakhalili** [beautifulinteractions/beautiful-react-diagrams#147]
**Is your feature request related to a problem? Please describe.**
It would be nice if links can be customized the same way nodes are. For example, I really need to have double links going outward, but I cannot achieve that because the way the library is written, links are black boxes.

**Comment by obadakhalili** [comment]
And ports are not enough because a) not very convenient, b) they can't be connected while initializing the data.

**Comment by stevechappell2000** [comment]
Not sure why you cannot connect while initializing. Define the links[ input: xx, output: yy]

**Comment by obadakhalili** [comment]
Completely missed the fact that I can have ports in inputs, not just nodes. Thanks.
