### ISSUE TITLE
Zoom In / Out

### ISSUE THREAD

**Issue by hicham17** [beautifulinteractions/beautiful-react-diagrams#17]
Hello

Thanks for the great lib!
is there a way to have a Zoom in / Zoom out feature with the existing lib or is is something new that should be developed as a new feature?

I am interested in

- Adding a Zoom in / out buttons to my canvas
- Activating Zoom in / out with the mouse scroll 

Thanks in advance for your help :)
Hicham

**Comment by antonioru** [comment]
Hi @hicham17 
thank you for opening the issue, the ZoomIn/ZoomOut feature is definitely in the TODO list but I haven't had the opportunity to start developing it yet, so - at the moment - it's something that should be developed from scratch. 

Feel free to propose any development approach and possibly open a pull request

**Comment by hicham17** [comment]
thanks a lot for your quick feedback!

**Comment by antonioru** [comment]
@hicham17 you are welcome! 

I hope I can deliver this feature as soon as possible as it's something we are currently using on few internal projects, I'll possibly keep you posted

thank you

**Comment by antonioru** [comment]
Hi @hicham17 just a quick message to tell you the feature you've requested it's currently under development 

#48

**Comment by hicham17** [comment]
Hello Antonio
This awesome news, thanks! 🥇

**Comment by anhpt-bss** [comment]
I hope this feature will release as soon as possible. thanks

**Comment by Flcwl** [comment]
Why the code is loss in `master` branch?

**Comment by omidgharib** [comment]
same issue here why current version  doesn't support this

**Comment by jupcan** [comment]
@antonioru think this somehow is lost on master branch? thanks for your great work!
