### ISSUE TITLE
Live Playground Link in README.MD broken

### ISSUE THREAD

**Issue by technicallynick** [beautifulinteractions/beautiful-react-diagrams#63]
Title is self explanatory. Clicking the link leads to a 404 Not Found message from github.

**Comment by chrispyduck** [comment]
It should point to https://beautifulinteractions.github.io/beautiful-react-diagrams. It looks like the repository was moved.

**Comment by gunar** [comment]
It points me to the documentation but I still don't see the live playground though.

Perhaps it should point [here](https://beautifulinteractions.github.io/beautiful-react-diagrams/#/Diagram%20Component) instead?
