### ISSUE TITLE
Broken link for "gh-pages"

### ISSUE THREAD

**Issue by madhankumar028** [beautifulinteractions/beautiful-react-diagrams#65]
**Describe the bug**
I guess the username has been changed, it would be better if you can fix the gh-pages link to this [one](https://beautifulinteractions.github.io/beautiful-react-diagrams/). 

**To Reproduce**
Steps to reproduce the behavior: NA

**Comment by antonioru** [comment]
Hello @madhankumar028 thank you for reporting this issue, yes the link in the repository description was broken.
I just fixed it 
thanks :)
