### ISSUE TITLE
How to dynamically add ports?

### ISSUE THREAD

**Issue by feddot2517** [beautifulinteractions/beautiful-react-diagrams#75]
Please help me how to dynamically add ports to a node?

**Comment by antonioru** [comment]
Hello @feddot2517 
at the moment we don't have any example on how to dynamically add ports, but you can simply add a port by programmatically change the Diagram schema. 

Please feel free to open a PR with an example about this

**Comment by feddot2517** [comment]
I did this: programmatically changed the scheme - added a new port to the target node. But there was a problem with drag & drop, because there is a dependence on the starting sizes (height / width) of the node. I decided this by making a drag area for each node, and now in my project i can move a node only by this area.. Thanks.

**Comment by antonioru** [comment]
thank you @feddot2517

**Comment by andriy-kdp** [comment]
> I did this: programmatically changed the scheme - added a new port to the target node. But there was a problem with drag & drop, because there is a dependence on the starting sizes (height / width) of the node. I decided this by making a drag area for each node, and now in my project i can move a node only by this area.. Thanks.

can you share your solution with drag area?

**Comment by feddot2517** [comment]
> > I did this: programmatically changed the scheme - added a new port to the target node. But there was a problem with drag & drop, because there is a dependence on the starting sizes (height / width) of the node. I decided this by making a drag area for each node, and now in my project i can move a node only by this area.. Thanks.
> 
> can you share your solution with drag area?

you can test that fork https://github.com/feddot2517/beautiful-react-diagrams, or look at that file on line 63 https://github.com/feddot2517/beautiful-react-diagrams/blob/master/src/Diagram/DiagramNode/DiagramNode.js
